INSERT INTO music
 (artist, album-artist, album, genre, year)
 VALUES
 ("","","","",""),
("The Feeling"," ","Twelve Stops And Home","Pop","2006"),
("The Rolling Stones"," ","Sticky Fingers","Rock","1971"),
("The Rolling Stones"," ","Beggars Banquet","Rock","1968"),
("Immer Neant","","94","Rock","1994"),
("Money Mark"," ","Push The Button","Electronic","1998"),
("Elbow"," ","A Cast of Thousands"," ","2003"),
("Elbow"," ","The Seldom Seen Kid"," ","2008"),
("fox incaico","Andes Music","Andes Music","Blues"," "),
("The Smashing Pumpkins","","Mellon Collie and the Infinite Sadness","Rock","1995"),
("The Smashing Pumpkins","","Mellon Collie And The Infinite Sadness Twilight To Starlight","Alternative Rock","1995"),
(" "," "," "," "," "),
("Smashing Pumpkins"," ","Siamese Dream","General Alternative","1993"),
("Primal Scream","Primal Scream","Screamadelica","Rock","1991"),
("Afro Celt Sound System","","Release","World Music","1999"),
("Ian Brown"," ","Music of the Spheres","Alternative","2001"),
("Beastie Boys"," ","The In Sound From Way Out!","Hip-Hop","1996"),
("Supergrass","","Supergrass","Other","1999"),
("Supergrass","","I Should Coco","BritPop","1995"),
("Supergrass","","In It For The Money","BritPop","1997"),
("Goldie Lookin Chain","Goldie Lookin Chain","Greatest Hit","Trip-Ho"," "),
("Goldie Lookin Chain","Goldie Lookin Chain","Greatest Hits","Trip-Ho"," "),
("Moloko","","Do You Like My Tight Sweater","Other","1995"),
("The Raconteurs"," ","Broken Boy Soldiers","Indie","2006"),
("The Raconteurs","","Consolers Of The Lonely","Blues"," "),
("Smashing Pumpkins"," ","Rotten Apples - Greatest Hits"," ","2001"),
("Smashing Pumpkins"," ","Mellon Collie And The Infinite Sadness - Dawn To Dusk [Disc 1]","General Alternative","1995"),
("Smashing Pumpkins"," ","Mellon Collie And The Infinite Sadness - Twilight To Starlight [Disc 2]","General Alternative","1995"),
("The Revels","Pulp Fiction Soundtrack","Pulp Fiction","Soundtrack","1994"),
("Chingon","Chingon","Mexican_Spaghetti_Western","Rock","2004"),
("Air","","Moon Safari","Electronic","1998"),
("Groove Armada","","Vertigo","Groove - Funky","1999"),
("Butch Cassidy Sound System","","Groove Armada Presents","Dance","2005"),
("Groove Armada","","Lovebox","Dance","2002"),
("Barry White"," ","Back To Mine","Other","2000"),
("Groove Armada","","Goodbye Country (Hello Nightclub)","Electronic","2001"),
("Groove Armada"," ","Black Light","Electronica","2010"),
("Pop Will Eat Itself","Pop Will Eat Itself","Dos Dedos Mis Amigos","Rock","1994"),
("Massive Attack"," ","Mezzanine","Trip-Hop","1998"),
("Massive Attack","Massive Attack","100th Window (Advance)","Ambient","2003"),
("Massive Attack"," ","Blue Lines","Trip-Hop","1991"),
("Leftfield"," ","Rhythm and Stealth","Electronic","1999"),
("Trikaal","","Trikaal 3, Global Waves","Fusion","2006"),
(" "," ","Unknown album (04/10/2014 23:29:48)"," "," "),
("Isaac Hayes","Isaac Hayes","Shaft - Soundtrack","Soundtrack","1971"),
("Alan Reeves, Phil Steele and P"," ","Kill Bill Volume 2","Soundtrack","2004"),
("Nancy Sinatra"," ","Kill Bill Volume 1","Soundtrack","2003"),
("Gomez"," ","Liquid Skin","Other","1999"),
("Gomez","","Bring It On","Rock","1998"),
("The Bees"," ","Free The Bees","Indie","2004"),
("PJ Harvey","","Stories From The City, Stories From The Sea","Rock","2000"),
("PJ Harvey"," ","Let England Shake","Rock","2011"),
("Frank Black","Crime And Punishment","Crime And Punishment","Soundtrack","2001"),
("Røyksopp"," ","The Understanding","Electronic","2005"),
("Royksopp","Röyksopp","Melody A.M.","Ambient","2001"),
("Led Zeppelin","Led Zeppelin","Mothership","Rock","2007"),
("Thievery Corporation"," ","The Outernational Sound","Electronic","2004"),
("The Trespassers","","Road Time Live in California","Country","2012"),
("Senser","Senser","Stacked Up","Misc","1994"),
("Sonic Youth","Sonic Youth","Daydream Nation","Rock","2007"),
("Sonic Youth","Sonic Youth","Daydream Nation, Disc 2","Rock","2007"),
("Sonic Youth"," ","Dirty"," "," "),
("Björk","","Debut","Pop","1993"),
("Avenged Sevenfold","Avenged Sevenfold","Nightmare [Explicit]","Rock","2010"),
("Avenged Sevenfold","Avenged Sevenfold","Avenged Sevenfold","Nu-Metal","2005"),
("Avenged Sevenfold","Avenged Sevenfold","Hail to the King","Rock","2013"),
("Avenged Sevenfold","Avenged Sevenfold","City Of Evil","Nu-Metal","2005"),
("Dinosaur Jr","","Green Mind","Alternative","1991"),
("The Fratellis","","Costello Music","Alternative Rock","2006"),
("Pulp"," ","This Is Hardcore (Limited UK Issue With This Is Glastonbury)","Alternative","1998"),
("Pulp"," ","This Is Hardcore (Limited UK Issue With This Is Glastonbury) - CD2 - This Is Glastonbury","Alternative","1998"),
("Pulp"," ","Different Class","Pop","1995"),
("The Offspring"," ","Smash"," "," "),
("The Immediate"," ","The Immediate"," "," "),
("Madder Rose"," ","Bring It Down","Other"," "),
("Madder Rose"," ","Panic On","Rock"," "),
("Madder Rose","Madder Rose","Tragic Magic","Rock","1997 06 24"),
("Them Crooked Vultures","Them Crooked Vultures","Them Crooked Vultures","Metal","2009"),
("Them Crooked Vultures"," ","Mind Eraser, No Chaser / Hwy 1 [Digital 45]","Rock","2010-04-20 07:00"),
("Them Crooked Vultures","Them Crooked Vultures","2010-05-18 - Chicago","Unknown"," "),
("Red Snapper","Red Snapper","Our Aim Is To Satisfy Red Snapper","Electronica & Dance","2000"),
("Ash","","1977","Rock","1996"),
("Jellyfish","","Spilt Milk","Rock","1993"),
("Jellyfish"," ","Bellybutton","Rock & Roll","1990"),
("The Doors"," ","Morrison Hotel"," ","1970"),
("The Doors","","The Soft Parade","Classic Rock","1969"),
("The Doors"," ","Waiting For The Sun"," ","1968"),
("The Doors","The Doors","The Doors (DCC)","Rock","1967"),
("The Doors","","Strange Days","Blues"," "),
("The Doors"," ","L.A.Woman"," ","1971"),
("Pavement"," ","Wowee Zowee","Indie Rock","1995"),
("Pavement","Pavement","Crooked Rain, Crooked Rain","Rock","1994"),
("Nirvana","","In Utero","Grunge","1993"),
("Nirvana","","Nevermind","Grunge","1991"),
("Nirvana","Nirvana","MTV Unplugged in New York","Alternative","1994"),
("Dodgy","Dodgy","Homegrown","Rock","1995"),
("Basement Jaxx"," ","Kish Kash","Club-House","2003"),
("Basement Jaxx"," ","Remedy","Electronica","1999"),
("KT Tunstall"," ","Eye to the Telescope","Rock","2004"),
("Foo Fighters","","The Colour And The Shape","Rock","1997"),
("Z Rollers","Mixmag","Not Forgotten - Greatest Dancefloor Moments 1990-2000 (Mixmag)","Club","1989"),
("The Brand New Heavies"," ","The Brand New Heavies","Soul","1992"),
("Jimi Hendrix"," ","Are You Experienced"," "," "),
("Jimi Hendrix"," ","Electric Ladyland"," "," "),
("Jimi Hendrix"," ","Axis Bold As Love"," "," "),
("Jimi Hendrix"," ","Band of Gypsies"," "," "),
("Beatles","","Rubber Soul","Rock","1965"),
("The Beatles","","Sgt Pepper's Lonely Hearts Club Band","Rock","1967"),
("The Beatles","","Revolver","Rock","1966"),
("The Beatles","","Abbey Road","PopRock","1969"),
("Beatles","","Help","Rock","1965"),
("New Order"," ","Power, Corruption & Lies","Wave","1983"),
("Todd Rundgren"," ","A Wizard, A True Star"," "," "),
("Pixies","","Complete B-Sides","Blues"," "),
("Pixies"," ","Doolittle (MFSL)","Alternative Rock","1989"),
("Pixies"," ","Subbacultcha"," "," "),
("Pixies"," ","Pixies At The BBC"," "," "),
("Pixies"," ","at the BBC","Pop","1999"),
("Pixies","Pixies","Trompe Le Monde","Rock"," "),
("Pixies"," ","Complete 'B' Sides","Punk Rock","2001"),
("Pixies","","Bossanova","Blues"," "),
("Pixies","Pixies","Death to the pixies","Rock","1997"),
("Pixies","Pixies","Death To the Pixies (DISK 1)","Rock","1997"),
("Pixies"," ","Timless stars"," "," "),
("Pixies","","At the BBC","Blues"," "),
("Pixies","","Death To The Pixies (Live CD)","Blues"," "),
("Pixies","","Surfer Rosa-Come On Pilgrim","Blues"," "),
("Pixies"," ","Planet of Sound"," "," "),
("UNKLE"," ","UNKLE"," ","2004"),
("UNKLE","UNKLE","War Stories","Electronic","2007"),
("UNKLE","UNKLE","Where Did The Night Fall","Electronic","2010"),
("Echo & The Bunnymen"," ","Ocean Rain","Alt. Rock","1984"),
("R.E.M."," ","Out Of Time","Alternative","1991"),
("R.E.M."," ","Green","Rock","1988"),
("REM"," ","Automatic for the People","Alternative","1992"),
("Blur","","The Great Escape","BritPop","1995"),
("Blur","","Modern Life Is Rubbish","Pop Rock","1993"),
("Blur","","Parklife","Rock","1994"),
("Blur","","Blur","Rock","1997"),
("Blur","","13","BritPop","1999"),
("Orbital","","02 Brown Album","Electronic","1993"),
("Orbital","","Snivilisation","Electronic","1994"),
("Orbital"," ","Diversions"," "," "),
("The Specials","Orbital","The Bedroom Sessions","Eletronica","2002"),
("Orbital"," ","Work 1989 - 2002","Techno","2002"),
("Orbital","Orbital","Blue Album [UK]","General Techno","2004"),
("Orbital"," ","The Altogether","Synthpop","2001"),
("Orbital","","In Sides","Electronic","1996"),
("Orbital","","The Middle Of Nowhere","Techno","1999"),
("David Bowie","David Bowie","Live at Glastonbury 2000","Rock","2000"),
("David Bowie","","Aladdin Sane","Pop","1973"),
("David Bowie"," ","Diamond Dogs","Rock","1973"),
("David Bowie","","Ziggy Stardust","Rock","1900"),
("David Bowie","","Hunky Dory","Folk-Rock","1971"),
("David Bowie"," ","Low","Rock","1977"),
("Andes Music Instrumental"," ","Andes Music Instrumental","Género desconocido"," "),
("The Charlatans","","Tellin' Stories","Rock","1997"),
("The Charlatans","","The Charlatans","Indie","1995"),
("Elastica","","Elastica","Blues"," "),
("The Velvet Underground"," ","Peel Slowly And See","Avant Rock","1995"),
("The Velvet Underground"," ","Loaded","Psychedelic Rock","1970"),
("Dreadzone","Dreadzone","Earth Angel 12""," "," "),
("Dreadzone","Dreadzone","Second Light","General Reggae","1995"),
("Dreadzone","Dreadzone","Sound","Dub","2001"),
("Dreadzone","Dreadzone","Dreadzone: Biological Radio","General Reggae","1997"),
("Musica Traditional de los Andes"," ","Ñanda Mañachi","Género desconocido"," "),
("The Beach Boys"," ","Pet Sounds","Pop","2000"),
("The Beach Boys","The Beach Boys","The Smile Sessions","Rock","2012"),
("The Beach Boys"," ","Smiley Smile - Wild Honey","Pop","1990"),
("Beach Boys"," ","Surf's Up","Rock","1971"),
("The Bluetones","","Expecting To Fly","Indie","1996"),
("Weezer","","Weezer (Blue Album)","Rock","1994"),
("Soundgarden"," ","Superunknown","Alternative\Rock","1994"),
("Soundgarden"," ","Badmotorfinger","Alternative\Rock","1991"),
("Underworld","Café Del Mar","Café del Mar Vol 1","Ambient","1994"),
("Caia"," ","Cafe Del Mar 35th Anniversary 1980-2015","New Age","2014"),
("4 Wings","Café Del Mar","Café del Mar Vol 5","Ambient","1998"),
("DZihan & Kamien","Café Del Mar","Café Del Mar Vol 6","Dream Dance","1999"),
("Janes Addiction"," ","Nothing's Shocking","Hard Rock","1988"),
("Jane's Addiction","Jane's Addiction","Jane's Addiction","Rock","1991"),
("Joy Division"," ","Closer","Rock","1980"),
("Asian Dub Foundation","","Community Music","DanceReggae","2000"),
("Gorillaz","Gorillaz","Gorillaz","Rock","2001"),
("Kid British","","Kid British","Unknown","2011"),
("Throwing Muses","Throwing Muses","Red Heaven","Rock","1992"),
("Editors"," ","The Back Room","Indie","2005"),
("TOO MANY ZOOZ","TOO MANY ZOOZ","Brasshouse Volume 1: Survival of the Flyest"," ","2014"),
("TOO MANY ZOOZ","TOO MANY ZOOZ","FANIMALS EP"," ","2014"),
("TOO MANY ZOOZ","TOO MANY ZOOZ","The Internet EP"," ","2015"),
("TOO MANY ZOOZ","TOO MANY ZOOZ","F NOTE"," ","2014"),
("dEUS"," ","The Ideal Crash","Alternative","1999"),
("Rafo Raez"," ","Trovadikxion","Acoustic","2007"),
("Flaming Lips"," ","Yoshimi Battles The Pink Robots","New Age","2002"),
("Sleater-Kinney","Sleater-Kinney","The Woods","Rock","2005"),
("Sleater-Kinney","Sleater-Kinney","All Hands On The Bad One","Rock","2000"),
("Sleater-Kinney","Sleater-Kinney","Dig Me Out","Rock","1997"),
("Sleater-Kinney","Sleater-Kinney","The Hot Rock","Rock","1999"),
("Sleater-Kinney","Sleater-Kinney","Call The Doctor","Rock","1996"),
("Sleater-Kinney","Sleater-Kinney","Get Up (Single)","Rock","1998"),
("Sleater-Kinney","Sleater-Kinney","Off With Your Head (Single)","Rock","2002"),
("Sleater-Kinney","Sleater-Kinney","One Beat","Rock","2002"),
("Sleater-Kinney","Sleater-Kinney","Sleater-Kinney","General Indie Rock","1996"),
("John Martyn"," ","Solid Air","FolkJazz","1973"),
("Mr Scruff"," ","Keep It Unreal","Trip-Hop","2002"),
("Arctic Monkeys","Arctic Monkeys","Suck It And See","Alternative","2011"),
("Arctic Monkeys","Arctic Monkeys","Cornerstone","Indie","2009"),
("Arctic Monkeys","Arctic Monkeys","Do I Wanna Know?","Indie Rock","2013"),
("Arctic Monkeys"," ","Don't Sit Down 'Cause I've Moved Your Chair","Alternative","2011"),
("Arctic Monkeys","Arctic Monkeys","Why'd You Only Call Me When You're High?","Pop Rock","2013"),
("Arctic Monekys"," ","My Propeller","Indie Rock","2010"),
("Arctic Monkeys"," ","Humbug [Japanese]","Alternative","2009"),
("Miles Kane and the Death Ramps"," ","The Hellcat Spangled Shalalala","Alternative","2011"),
("Alex Turner"," ","Submarine","Soundtrack","2011"),
("Arctic Monkeys"," ","Humbug","","2009"),
("Arctic Monkeys"," ","Suck It and See","Alternative","2011"),
("Arctic Monkeys"," ","When The Sun Goes Down (CD Single)","Alternative & Punk","2006"),
("Arctic Monkeys"," ","Favourite Worst Nightmare"," "," "),
("Arctic Monkeys"," ","Live In Texas (7 June 2006)","Indie","2008"),
("Arctic Monkeys"," ","R U Mine? / Electricity","Alternative","2012"),
("Richard Hawley and the Death Ramps"," ","Black Treacle","Alternative","2011"),
("Arctic Monkeys"," ","Whatever People Say I Am, That's What I'm Not","Indie","2006"),
("Arctic Monkeys"," ","I Bet You Look Good On The Dancefloor","Indie Rock","2005"),
("Love"," ","Forever Changes"," ","1900"),
("Beth Orton","","Central Reservation","Folk-Rock","1999"),
("Beth Orton"," ","Trailer Park","Folk","1996"),
("Faze Action"," ","Plans & Designs","Dance","1997"),
("Kaiser Chiefs","Kaiser Chiefs","Employment","Rock","2005"),
("Belle & Sebastian","Belle & Sebastian","Dear Catastrophe Waitress","Rock","2003"),
("Belle & Sebastian","","If You're Feeling Sinister","Pop","1996"),
("Belle & Sebastian","Belle & Sebastian","The Life Pursuit","Rock","2006"),
("Belle & Sebastian"," ","Tigermilk"," ","1996"),
("Belle & Sebastian"," ","Fold Your Hands Child, You Walk Like A Peasant","Indie","2000"),
("Caravan Palace"," ","<I°_°I>","Electro Swing","2015"),
("The Stone Roses","","Second Coming","Alternative","1994"),
("The Stone Roses","","The Stone Roses Anniversary Edition (CD 1)","Rock","1999"),
("The Stone Roses","","The Stone Roses Anniversary Edition (CD 2)","Indie","1999"),
("Guillemots"," ","Through The Window Pane","Alternative & Punk","2006"),
("Guillemots"," ","From the Cliffs","Indie","2006"),
